# This code is generated by ChatGPT.

#!/usr/bin/env python3
import os
import argparse

def swap_chains_in_pdb(input_file, output_file):
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Split file into header, atoms, and footer
    header, atoms, footer = [], [], []
    seen_atoms = False

    for line in lines:
        if line.startswith(("ATOM", "HETATM")):
            atoms.append(line)
            seen_atoms = True
        elif not seen_atoms:
            header.append(line)  # before first ATOM/HETATM
        else:
            footer.append(line)  # after last ATOM/HETATM

    # Separate chains
    chainA, chainB = [], []
    for line in atoms:
        chain_id = line[21]
        if chain_id == "A":
            chainA.append(line)
        elif chain_id == "B":
            chainB.append(line)

    if not chainA or not chainB:
        print(f"Skipping {input_file}: does not contain both chains A and B.")
        return

    # Swap: A <-> B
    swapped = []
    new_atom_serial = 1
    next_resnum = 1  # global residue counter

    def renumber_chain(chain_lines, new_chain_id):
        nonlocal new_atom_serial, next_resnum
        new_lines = []
        res_map = {}

        for line in chain_lines:
            atom_serial = new_atom_serial
            new_atom_serial += 1

            old_resnum = int(line[22:26])
            if old_resnum not in res_map:
                res_map[old_resnum] = next_resnum
                next_resnum += 1

            new_resnum = res_map[old_resnum]

            # Rebuild line with updated atom serial, chain ID, residue number
            newline = (
                line[:6] +
                f"{atom_serial:5d}" +          # atom serial
                line[11:21] +
                new_chain_id +
                f"{new_resnum:4d}" +          # residue number
                line[26:]
            )
            new_lines.append(newline)
        return new_lines

    # Swap chains.
    swapped.extend(renumber_chain(chainB, "A"))  # B → A
    swapped.extend(renumber_chain(chainA, "B"))  # A → B

    # Write output: header → atoms → footer
    with open(output_file, 'w') as out:
        for l in header:
            out.write(l)
        for l in swapped:
            out.write(l)
        for l in footer:
            out.write(l)


def main():
    parser = argparse.ArgumentParser(description="Swap chains A and B in PDB files, renumber atoms/residues, preserve headers.")
    parser.add_argument("-i", "--input", help="Input PDB file")
    parser.add_argument("-d", "--directory", help="Directory containing PDB files")
    parser.add_argument("-o", "--output", help="Output file (for single input). If not given, will overwrite input.")
    args = parser.parse_args()

    if args.input and args.directory:
        parser.error("Specify either an input file OR a directory, not both.")

    if args.input:
        output_file = args.output if args.output else args.input
        swap_chains_in_pdb(args.input, output_file)

    elif args.directory:
        for fname in os.listdir(args.directory):
            if fname.lower().endswith(".pdb"):
                infile = os.path.join(args.directory, fname)
                outfile = infile  # overwrite
                swap_chains_in_pdb(infile, outfile)
    else:
        parser.error("You must specify either an input file with -i or a directory with -d.")


if __name__ == "__main__":
    main()
